### ISSUE TITLE
branca decode does not handle binary data

### ISSUE THREAD

**Issue by ganwell** [return/branca#10]
1. Take another branca implementation (eg. pybranca)
2. Encode binary data

```python
f = Branca(fromstring(key))
ct = f.encode(b"\x80")
```
3. Pass `ct` do decode in this implementation

-> it will return b'\xef\xbf\xbd'

The spec allows binary data:

`..... serialized by MessagePack or Protocol Buffers.` from branca.io

**Comment by brycx** [comment]
This seems to be due to the expectation that the encoded data is valid UTF-8: 
https://github.com/return/branca/blob/34758ab5c82c9f7446e9d2dc9a563934bff7f3c2/src/lib.rs#L448

This is compatible with this implementation's `encode` function, which takes `&str`. But if another implementation is used to encode non-valid UTF-8, then the above happens ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=970d1ea59292d24dcb009194df02e9cc)).

`decode()` could return `Vec<u8>` instead of `String` to solve this.

**Comment by J-F-Liu** [comment]
@brycx Suggest use `AsRef<[u8]>` in encode function.
```rust
pub fn encode<T: AsRef<[u8]>>(data: T, key: &[u8], timestamp: u32) -> Result<String, BrancaError>
```

**Comment by brycx** [comment]
@J-F-Liu Thank you for the suggestion. I think your proposal could be a good idea. However, @return currently is very busy and has given me permission to merge and update the crate with the purpose of fixing current bugs. As there were no generic parameters used in function signatures before, I will not add these now. This is simply to change as little as possible in order to fix the issue and stick to the current API as much as possible. I will open an issue for generic parameters, which @return can then decide upon once they have time again.
